server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: ConfigServer
          uri: https://github.com/dsimdev/spring-microservicios
          search-paths: config-data
  application:
    name: config-service
